# Nome da nossa aplicação
spring.application.name=despachante-api

# 1. Configuração do Banco de Dados H2 (Salvando em arquivo local)
# O "./dados_despachante" cria um arquivo na própria pasta do projeto para não perder os dados ao desligar
spring.datasource.url=jdbc:h2:file:./dados_despachante
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configuração do Hibernate (A mágica que cria as tabelas)
# O "update" faz o Java ler os seus Models e criar as colunas sozinho no banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# 3. Habilitar a interface do H2 no navegador (Para a gente ver as tabelas prontas depois)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console